### ISSUE TITLE
mediamtx does not build

### ISSUE THREAD

**Issue by MaxTheMooshroom** [nucleus-labs/doorbellian-docker#1]
Error:
`build github.com/bluenviron/mediamtx: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element`

Found on line 64 of the Dockerfile. I've tried several go installs, nothing works. None of the following packages compile mediamtx: `gccgo-go`/`golang`/`golang-go`

**Comment by Ranjeetdhu** [comment]
I am unable to install or download in rpi mediamtx??what should I do
